### ISSUE TITLE
Not available on nest.land

### ISSUE THREAD

**Issue by borsemayur2** [herudi/dero#1]
I tried it quickly it seems very simple and elegant. I didn't find it in nest.land. Do we have plans for publishing it on nest.land.

P.S. Created this issue because discussions section is not enabled at the moment.

**Comment by herudi** [comment]
Thanks for trying dero and giving advice. I think it's a brilliant idea to include Dero in Nest.land. maybe in the near future i will put it in nest.land. 
> Note: this issue will be closed if Dero is already in nest.land. 

Thank you again for giving advice.

**Comment by herudi** [comment]
Now, Dero available on nest.land => https://nest.land/package/dero
