### ISSUE TITLE
is there dero middlwear for generate swagger 

### ISSUE THREAD

**Issue by elycheikhsmail** [herudi/dero#2]
like in foal ts for example

**Comment by herudi** [comment]
@elycheikhsmail Sounds good. next time I will try to make the integration with swagger. for now not supported. thanks

**Comment by elycheikhsmail** [comment]
> @elycheikhsmail Sounds good. next time I will try to make the integration with swagger. for now not supported. thanks

thanks, this is great project using best pratic of P.O.O and decorato patter and D.I

**Comment by elycheikhsmail** [comment]
deno_swagger is created

**Comment by herudi** [comment]
Yeah,, https://github.com/herudi/dero_swagger
