### ISSUE TITLE
Syntax error in deps.ts 

### ISSUE THREAD

**Issue by YuriiShchyrba** [herudi/dero#6]
One of your exports using old version of syntax :
export { serve, serveTLS, Server } from "https://deno.land/std/http/server.ts";
But they changed it for lowerCase in serveTLS -> serveTls (now what they are using), can you update please ?

**Comment by herudi** [comment]
Please give me info about dero version.

Current release [1.2.4](https://deno.land/x/dero@1.2.4)

**Comment by YuriiShchyrba** [comment]
I was using version 0.2.7 , didnt pay attention that there is upgrade, everything is working

**Comment by herudi** [comment]
yeah.
